name: generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"  # jalan tiap hari jam 7 pagi WIB
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Glenferdinza
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the output files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
